version: '3.5'

services:
  database:
    image: postgres:15.4
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "{DATABASE_PORT}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
