export enum UserErrorCodes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS = "PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS",
}
